### ISSUE TITLE
First Test Issue

### ISSUE THREAD

**Issue by sunnydutt12** [abbasali-io/tdp-global#1]
This is a first test issue for TDP app
![Artboard 11](https://github.com/abbasali-io/tdp-global/assets/83697836/d6c6875c-528c-4c2c-8e8c-b6469a9e50b1)

**Comment by abbasali-io** [comment]
changed the label to bug

**Comment by sunnydutt12** [comment]
Ok its done

**Comment by sunnydutt12** [comment]
hanji
