### ISSUE TITLE
Asterisk after the warehouse postcodes!! - Issue keeps re-emerging

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#13]
This issue keeps re-emerging, we keep getting the Asterisk after the postcode!, it was fixed, but the fix did not last.

<img width="861" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/4651bac9-f693-4796-b2ec-52b647278cc1">

**Comment by abbasali-io** [comment]
@Rahbul is going to fix this again :)

**Comment by Rahbul** [comment]
@abbasali-io This has been fixed now.
