### ISSUE TITLE
IMPORTANT: Warehouse Products needs to be Fixed

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#14]
We are getting all the products for 'Paid Warehouse' and NONE from the other 'Free Warehouses' if you refer to the image below, these are the products we are receiving from API. You would notice that there are NO date tins or ajwa included, which are the products being delivered.

IMPORTANT: We suspect that we will also get ALL the orders from these products as well, which will in turn create deliveries for the calendar and gift box items.

Pleasee Help!

<img width="346" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/e17ff6e8-b86e-479c-8ec3-e15d86760535">

**Comment by Rahbul** [comment]
1-Now only those products show that assign to the free warehouses
2- All Api's  responses success true and false you have manage code effectively on your end
