### ISSUE TITLE
IMPORTANT: Order Item products needs to be fixed

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#15]
IMPORTANT: for the online orders, we are getting the items that are not supposed to be delivered! Having these items in the order will create deliveries for these items and will cause massive confusion with over 1k volunteers.

Request: please filter the items before sending in the following API

<img width="843" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/214fc881-3884-4bd3-8cf3-8ba3535c9040">

**Comment by abbasali-io** [comment]
@mohsinnaeem21 bhai approved the fix, @Rahbul will fix and will filter the paid warehouse items from the order

**Comment by Rahbul** [comment]
@abbasali-io Bhai, Now display the orders only that are associated with free shipping. Kindly verify on your end

**Comment by abbasali-io** [comment]
We are still getting items in the order that are not related, kindly refer to the screenshot below, @mohsinnaeem21 

@Rahbul I ll appreciate it if you could test the solution before closing the issue.

<img width="944" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/d61d378a-27e4-4dad-8844-af11de09ede1">

**Comment by Rahbul** [comment]
@abbasali-io Bhai please check

![image](https://github.com/abbasali-io/tdp-global/assets/157615726/2e68d6c9-820f-4cb8-bcde-78d0f58fe832)
