### ISSUE TITLE
Adding Lead function not working

### ISSUE THREAD

**Issue by zahid261** [abbasali-io/tdp-global#17]
Just tried to add Sam Ali as a Lead, nothing happens when the confirmation is pressed.
<img width="939" alt="Screenshot 2024-01-24 at 08 06 14" src="https://github.com/abbasali-io/tdp-global/assets/45424127/599abb9e-50a5-4a3b-81c6-c1de56430dde">

**Comment by sunnydutt12** [comment]
Zahid bhai it's fixed. Please try now. The user was already created in the auth directory while testing. I deleted it . it should work now. Thanks

**Comment by zahid261** [comment]
confirmed working
