### ISSUE TITLE
Delivery Optimization

### ISSUE THREAD

**Issue by sunnydutt12** [abbasali-io/tdp-global#18]
Delivery optimization is breaking down and not returning Optimized routes @abbasali-io

**Comment by abbasali-io** [comment]
dependent on #15 #14 

We are not getting the orders to create deliveries and test this function.

Will revisit once the above issues are fixed. so that we can crate deliveries and debug the optimization function.

**Comment by abbasali-io** [comment]
fixed will be released in build 46
