### ISSUE TITLE
Warehouse Postcodes updates API

### ISSUE THREAD

**Issue by sunnydutt12** [abbasali-io/tdp-global#19]
update warehouse postcodes API is returning 500 server error. @abbasali-io

**Comment by abbasali-io** [comment]
Dependency on #3 

we need to get confirmation on the JSON body from the portal, before making changes on the endpoint handling at Google Cloud Function. @Rahbul

**Comment by abbasali-io** [comment]
#21 is related to this as well

**Comment by Rahbul** [comment]
@abbasali-io Bhai I don't understand your requirements. Is this issue related to issue #3?

**Comment by sunnydutt12** [comment]
Yes it is related to issue #3 but anyways we are doing it manually now.
