### ISSUE TITLE
Admin order details : Add Graceful failure for API errors

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#20]
As per the error code for API, if the error code is 40*, provide a graceful error handling, by showing the message from the API 'message' section.

**Comment by sunnydutt12** [comment]
![Screenshot 2024-01-24 at 11 49 58 PM](https://github.com/abbasali-io/tdp-global/assets/83697836/0b78d1f8-e51e-4044-bdcb-750314b3b137)

Implemented just now...
