### ISSUE TITLE
Update Warehouse PostCodes

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#3]
If the warehouse changes the postcodes, either assign new ones or remove existing postcode coverage, the App needs to know about that so it can adjust accordingly for leads and volunteers.

This can be done by calling the following API:
https://updatewarehousepostcodes-[******}-uc.a.run.app

with the JSON body as follows:
{
    "tdp_auth_key": "[ the API key]",
    "wid": "57",     // warehouse portal is
    "postCode": [   // the set of current postcodes that this warehouse supports
        "NP26",
        "NP44",
        "NP19",
        "NP18",
        "NP20",
        "NP10"
    ]
}

Please could you test the above API and let us know if the result and status is according to the expectations for the API team

**Comment by abbasali-io** [comment]
discussed with @mohsinnaeem21 bhai, he will get back to us on the body of json payload.

**Comment by abbasali-io** [comment]
@mohsinnaeem21 bhai, let's look into this

**Comment by Rahbul** [comment]
@abbasali-io Bhai 
This kind of functionality is not possible in WooCommerce.
