### ISSUE TITLE
The API status for NOT-FOUND is wrongly giving Success code

### ISSUE THREAD

**Issue by abbasali-io** [abbasali-io/tdp-global#7]
We need to fix the status code, even there is an error, the API returns a status code of 200. 

Requirement: the api should give the status code according to the content and situation, in this case, a 404 code if no data found, as per the Restful HTTP documentation

<img width="929" alt="image" src="https://github.com/abbasali-io/tdp-global/assets/3590177/42ca7465-8301-443b-a0c3-1ffe728c7549">

**Comment by abbasali-io** [comment]
Ths status code shall be fixed for all APIs, @Rahbul bhai, correct?

**Comment by Rahbul** [comment]
@abbasali-io This has been fixed now.

![image](https://github.com/abbasali-io/tdp-global/assets/157615726/3c3c4d00-6f62-4a06-91f1-67f2a37a71fa)
